name: PR Reminder

on:
  schedule:
    - cron: "47 23,4,7,8,10 * * *"
  workflow_dispatch:

jobs:
  call-reusable-reminder:
    uses: 33-Auto/.github/.github/workflows/reusable-pr-reminder.yml@main
    
    secrets:
      # 조직 시크릿을 secrets 입력으로 전달
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # 조직 변수를 secrets 입력으로 전달
      SLACK_USER_MAP: ${{ secrets.SLACK_USER_MAP }}